# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "abdb2fe9e3a13b38c232a9ce9cb13607"
name = "editions-demo-testing"
handle = "editions-demo-testing"
application_url = "https://surfaces-volunteers-characters-cream.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "james-ui-extensions.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "unauthenticated_read_product_listings,write_cart_transforms,write_products"

[auth]
redirect_urls = [
  "https://surfaces-volunteers-characters-cream.trycloudflare.com/auth/callback",
  "https://surfaces-volunteers-characters-cream.trycloudflare.com/auth/shopify/callback",
  "https://surfaces-volunteers-characters-cream.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
