api_version = "2024-04"

[[extensions]]
type = "ui_extension"
name = "product-offer-ui"
handle = "product-offer-ui"

[[extensions.targeting]]
module = "./src/index.tsx"
target = "purchase.checkout.cart-line-list.render-after"

[extensions.capabilities]
api_access = true
